//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loaddataver01.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class employees_manager_ver2Entities : DbContext
    {
        public employees_manager_ver2Entities()
            : base("name=employees_manager_ver2Entities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<contactemployeeinfo> contactemployeeinfoes { get; set; }
        public virtual DbSet<employeedetail> employeedetails { get; set; }
        public virtual DbSet<qualification> qualifications { get; set; }
        public virtual DbSet<salaryinfo> salaryinfoes { get; set; }
        public virtual DbSet<timeinfo> timeinfoes { get; set; }
        public virtual DbSet<workhistory> workhistories { get; set; }
    }
}
