//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loaddataver01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qualification
    {
        public int idQualification { get; set; }
        public string employeeID { get; set; }
        public string experience { get; set; }
    
        public virtual employeedetail employeedetail { get; set; }
    }
}
