//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loaddataver01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salaryinfo
    {
        public int idSalaryInfo { get; set; }
        public string employeeID { get; set; }
        public Nullable<int> monthlySalary { get; set; }
        public Nullable<int> moneyCurrency { get; set; }
        public Nullable<int> moneyDeductions { get; set; }
        public Nullable<int> moneyInsurance { get; set; }
    }
}
